name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build extension
        run: |
          npm install
          npm run build

      - name: Publish to Visual Studio Code Marketplace
        uses: shikiyam/vsce-publish-action@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          vsix: "*.vsix"
