name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Publish to Visual Studio Code Marketplace
        run: vsce publish
